#!/bin/bash

if [[ "$1" == "--date" || "$1" == "-d" ]]; then
  date
elif [[ "$1" == "--logs" || "$1" == "-l" ]]; then
  if [[ -z "$2" ]]; then
    count=100
  else
    count=$2
  fi

  for ((i=1; i<=$count; i++)); do
    echo "log$i.txt" > log$i.txt
    echo "Skrypt: skrypt.sh" >> log$i.txt
    echo "Data: $(date)" >> log$i.txt
  done
elif [[ "$1" == "--help" || "$1" == "-h" ]]; then
  echo "Dostępne opcje:"
  echo "- skrypt.sh --date (-d): Wyświetla dzisiejszą datę."
  echo "- skrypt.sh --logs [liczba] (-l): Tworzy [liczba] plików logx.txt (domyślnie 100),"
  echo "  zapisuje nazwę pliku, nazwę skryptu i bieżącą datę."
else
  echo "Nieznana opcja. Użyj skrypt.sh --help, aby zobaczyć dostępne opcje."
fi

